# NumPy Practice

In [ ]:
%pip install numpy # To install numpy package

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np # Importing numpy package
 # How to check the version of the numpy package
print('numpy:', np.__version__)

numpy: 2.3.5


In [ ]:
numpyArray = np.array([1, 2, 3, 4, 5])
print(numpyArray)
doubledNumpyArray = numpyArray * 2 # This will double each element in the array. This wouldn't work with regular python lists. Numpy arrays support element-wise operations.
print(doubledNumpyArray)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [ ]:
# Multidimensional Arrays
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(matrix)
print("Element at row 1, column 2:", matrix[1, 2])  # Accessing element at row 1, column 2
print("First row:", matrix[0])  # Accessing the first row
print("Second column:", matrix[:, 1])  # Accessing the second column

# In normal python lists, we would access like [1][2] for row 1, column 2 but in numpy we can do it in a single step as shown above.

threeDArray = np.array([[[1, 2, 3], 
                         [4, 5, 6], 
                         [7, 8, 9]],

                         [[1, 2, 3], 
                          [4, 5, 6], 
                          [7, 8, 9]],
                            
                         [[1, 2, 3], 
                          [4, 5, 6], 
                          [7, 8, 9]]])
                        
print(threeDArray)
print("Element at (1, 0, 1):", threeDArray[0, 0, 1])  # Accessing element at (1, 0, 1) - (layer 1, row 0, column 1)
print("First layer:\n", threeDArray[0])  # Accessing the first layer
print("Second row of first layer:", threeDArray[0, 1])  # Accessing the second row of the first layer

operation  = threeDArray[0, 0, 0] + threeDArray[2, 1, 1]  # 1 + 5
print("Operation result:", operation)
print()


# Making a 3 letter word from an abcd multidemensional array
alphabets = np.array([[['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']],
                     [['j', 'k', 'l'], ['m', 'n', 'o'], ['p', 'q', 'r']],
                     [['s', 't', 'u'], ['v', 'w', 'x'], ['y', 'z', ' ']]])

word  = alphabets[0, 1, 0] + alphabets[1, 1, 2] + alphabets[0, 2, 0]
print("3 letter word formed:", word)

print(alphabets[0:2])  # Slicing the array to get a sub-array, 0 layer to 2-1 layer, so displays 1st layer and 2nd layer.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Element at (1, 0, 1): 2
First layer:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second row of first layer: [4 5 6]
Operation result: 6

3 letter word formed: dog
[[['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]

 [['j' 'k' 'l']
  ['m' 'n' 'o']
  ['p' 'q' 'r']]]


In [ ]:
# Scalar Arithmetic operations on Numpy Arrays
array1 = np.array([1,2,3])
print(array1 + 1)
print(array1 - 2)
print(array1 * 3)
print(array1 / 4)
print(array1 ** 5)


[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [9]:
# Vectorized Math funcs
array2 = np.array([1.01, 2.5, 3.99])

print(np.sqrt(array2))
print(np.round(array2))
print(np.pi)

radii = np.array([1, 2, 3])

print(f"Areas of circles with given radii: {np.pi * (radii ** 2)}")

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
3.141592653589793
Areas of circles with given radii: [ 3.14159265 12.56637061 28.27433388]


In [ ]:
# Comparison operators
scores = np.array([85, 90, 78, 92, 88])
passed = scores >= 80
print("Scores:", scores)
print("Passed:", passed)
scores[scores < 80] += 5 # Adding 5 bonus points to scores less than 80
print("Updated Scores:", scores)

print(scores[(scores > 85) & (scores < 90)]) # Scores greater than 85 and less than 90

print(np.where(scores > 90, "A", "B")) # Assigning grades based on scores using np.where

Scores: [85 90 78 92 88]
Passed: [ True  True False  True  True]
Updated Scores: [85 90 83 92 88]
[88]
['B' 'B' 'B' '92' 'B']


In [42]:
# Aggregate functions
data = np.array([10, 20, 30, 40, 50])
print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Max:", np.max(data))
print("Min:", np.min(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))

data2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Sum of each column:", np.sum(data2, axis=0))
print("Sum of each row:", np.sum(data2, axis=1))

print(data2.shape) # 3 rows and 3 columns
reshapedData = data2.reshape(1, 9) # Reshaping to 1 row and 9 columns
print("Reshaped Data:\n", reshapedData)

Sum: 150
Mean: 30.0
Max: 50
Min: 10
Standard Deviation: 14.142135623730951
Variance: 200.0
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
(3, 3)
Reshaped Data:
 [[1 2 3 4 5 6 7 8 9]]


In [32]:
# Random numbers

rng = np.random.default_rng(seed=1) # seed means the starting point for generating random numbers. Using same seed will give same random numbers.

print(rng.integers(low=1,high=7, size=10))  # Simulating 10 dice rolls (1-6)
print(rng.integers(low=1, high=101, size=(3, 2)))  # Generating a 3x2 array of random floats between 1 and 100

print(np.random.uniform(low=-1, high=1, size=5))  # Generating 5 random floats between -1 and 1

shuffleArray = np.array([1, 2, 3, 4, 5])
rng.shuffle(shuffleArray)  # Shuffling the array
print("Shuffled Array:", shuffleArray)

choice = rng.choice(['red', 'blue', 'green'], size=4, replace=True, p=[0.2, 0.5, 0.3]) # Randomly choosing 4 colors with given probabilities
print("Randomly chosen colors:", choice)

[3 4 5 6 1 1 5 6 2 2]
[[87 43]
 [28 83]
 [26 41]]
[-0.24325414 -0.17431514 -0.60066167 -0.14750241  0.17710884]
Shuffled Array: [2 1 4 5 3]
Randomly chosen colors: ['green' 'blue' 'blue' 'green']


In [ ]:
# dtype = keyword argument that tells NumPy what kind of values are stored in an array.
# Otherwise NumPy guesses the best data type based on your data
# Manually setting dtype improves performance and memory usage.

# integer (int8, int16, int32, int64)
# float (float16, float32, float64)
# boolean (bool_)
# string (str_, <U#) 
# object (object_)

newArray = np.array([1.1, 2.3, 3.1, 4.6, 5.9], dtype=np.float32)
print(newArray)

newArray = newArray.astype(np.int32)  # Converting to int32
print(newArray)

[1.1 2.3 3.1 4.6 5.9]
[1 2 3 4 5]


In [ ]:
# Creating a sequences of numbers using arange

sequence = np.arange(10, 21, 2) # Numbers from 10 to 20 with a step of 2
print(sequence)
print(sequence.size)  # Number of elements in the array
print(sequence.dtype)  # Data type of the elements in the array
print(sequence.ndim) # Checks dimensions of array

[10 12 14 16 18 20]
6
int64
1


In [ ]:
# Array modifications

sample = np.array([10, 20, 30, 40, 50, 60])
mod1 = np.insert(sample, 1, 15, axis=0) # Insertion of an element inside an array at the index specified.
print(mod1)

mod2 = np.append(sample, 70) # appending at the end of the list. 
print(mod2)

mod3 = np.delete(sample, 0, axis=0) # deleting an element at index specified. You can add axis or not, doesnt matter for 1d array, but you can add for 2d arrays.
print(mod3)

sample2 = np.array([70, 80, 90, 100, 110, 120])
mod4 = np.vstack((sample,sample2)) # Vertical stacking
mod5 = np.hstack((sample,sample2)) # Horizontal Stacking
print(mod4)
print(mod5)


mod6 = np.split(sample, 2) # Splits an array, first argument takes array and 2nd takes how many splits. There's also hsplit() and vsplit().
print(mod6)

[10 15 20 30 40 50 60]
[10 20 30 40 50 60 70]
[20 30 40 50 60]
[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]
[ 10  20  30  40  50  60  70  80  90 100 110 120]
[array([10, 20, 30]), array([40, 50, 60])]


In [ ]:
# Broadcasting
prices  =  np.array([100, 200, 300]) 
discount = 10
final_prices = prices - (prices * discount/100) # We dont need loops for Numpy.
print(final_prices)

# Matching dimensions: if arr1 = [1,2,3] and arr2 = [1,2,3] then adding is easy. It will be [2, 4, 6]
# arr1 + 1 also gives [2, 3, 4]
# For incompatible shapes, like [1,2,3] + [1,2]; this will throw an error. We can use reshape() in such cases.

# Matrix + Vector
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])
result = arr1 + arr2
print(result) # The addition happened row-wise. This happened because the dimensions, row-wise is same


[ 90. 180. 270.]
[[11 22 33]
 [14 25 36]]


In [ ]:
# Handling Missing Values
arr = np.array([1,2,np.nan,4,np.nan,6])
print(np.isnan(arr)) #Is there a Not A Number value? yes there is, also we cannot compare np.nan == np.nan values.

cleaned_arr = np.array(np.nan_to_num(arr, nan=0),dtype=np.int32)
print(cleaned_arr)

[False False  True False  True False]
float64
